[package]
name = "disk_analyzer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disk_analyzer"
path = "main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.7.3"
charts-rs = "0.2.0"